openapi: 3.0.0
info:
  title: Book API
  version: 1.0.0
components:
  schemas:
    Book:
      type: object
      properties:
        tag:
          description: |
          ОПИСАНИЕ КЛАССА
        id:
          type: string
        title:
          type: string
        author:
          type: string
